trigger:
- main

pool: my-pool

steps:


- task: Docker@2
  inputs:
    containerRegistry: 'my-registry'
    repository: 'library/2048'
    command: 'buildAndPush'
    Dockerfile: '2048-game/Dockerfile'
    buildContext: '2048-game'

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'cubik'
    namespace: 'default'
    manifests: '01_kubernetes_aks/app-deploy.yaml'