trigger:
- main

pool: my-pool
  agent.name: WIN10-Docker

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'my-registry'
    repository: 'repo'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: '/2048-game/'
    tags: '2048-game'
