trigger:
- main

pool: my-pool

variables:
  tag: '$(Build.BuildId)'

steps:


- task: Docker@2
  inputs:
    containerRegistry: 'my-registry'
    repository: 'library/2048'
    command: 'buildAndPush'
    Dockerfile: '2048-game/Dockerfile'
    tags: |
      $(tag)
      latest

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'cubik'
    namespace: 'default'
    manifests: '01_kubernetes_aks/app-deploy.yaml'
#    containers: 'azuredevops.test.dev/library/2048/web-game:$(tag)'
    