trigger:
- main

variables:
  tag: '$(Build.BuildId)'

stages: 
- stage: Build
  displayName: Build and Push Image
  jobs:
    - job: BuildandPush
      displayName: Build and Push
      pool: my-pool
      steps:
        - task: Docker@2
          displayName: Build and Image
          inputs:        
            containerRegistry: 'my-registry'
            repository: 'library/2048'
            command: 'buildAndPush'
            Dockerfile: '2048-game/Dockerfile'
            tags: |
              $(tag)
              latest
