trigger:
- main

pool: my-pool

steps:
  - 
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'cubik-default-1713699535548'
    namespace: 'default'
    manifests: '01_kubernetes_aks/app-deploy.yaml'
